import VideoType from "../../app/types/Video";

const mockVideoCardData: VideoType[] = [
  {
    videoId: "1",
    title: "test1",
    uploader: { nickname: "nobody" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
  },
  {
    videoId: "2",
    title: "test2",
    uploader: { nickname: "nobody" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
  },
  {
    videoId: "3",
    title: "test3",
    uploader: { nickname: "nobody" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
  },
  {
    videoId: "4",
    title: "test4",
    uploader: { nickname: "nobody" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
  },
  {
    videoId: "5",
    title: "test5",
    uploader: { nickname: "nobody" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
  },
  {
    videoId: "6",
    title: "test6",
    uploader: { nickname: "nobody" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
  },
  {
    videoId: "7",
    title: "test7",
    uploader: { nickname: "nobody" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
  },
  {
    videoId: "8",
    title: "test8",
    uploader: { nickname: "nobody" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
  },
  {
    videoId: "9",
    title: "test9",
    uploader: { nickname: "nobody" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
  },
  {
    videoId: "10",
    title: "test10",
    uploader: { nickname: "nobody" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
  },
];

export default mockVideoCardData;
