import VideoType from "../../app/types/Video";

const mockVideoCardData: VideoType[] = [
  {
    videoId: "1",
    title: "test1",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    likedData: [],
    starredData: {},
    length: 320,
  },
  {
    videoId: "2",
    title: "test2",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    likedData: [],
    starredData: {},
    length: 552642,
  },
  {
    videoId: "3",
    title: "test3",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    likedData: [],
    starredData: {},
    length: 32134,
  },
  {
    videoId: "4",
    title: "test4",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    likedData: [],
    starredData: {},
    length: 77,
  },
  {
    videoId: "5",
    title: "test5",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    likedData: [],
    starredData: {},
  },
  {
    videoId: "6",
    title: "test6",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    likedData: [],
    starredData: {},
    length: 1,
  },
  {
    videoId: "7",
    title: "test7",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    likedData: [],
    starredData: {},
    length: 32,
  },
  {
    videoId: "8",
    title: "test8",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    likedData: [],
    starredData: {},
    length: 523,
  },
  {
    videoId: "9",
    title: "test9",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    likedData: [],
    starredData: {},
  },
  {
    videoId: "10",
    title: "test10",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    likedData: [],
    starredData: {},
  },
  {
    videoId: "11",
    title: "test11",
    uploader: { nickname: "nobody", profilePictureUrl: "http://" },
    viewCount: 4567890,
    starCount: 123,
    likeCount: 0,
    thumbnailUrl: "gs://que-backend-dev.appspot.com/videos/thumbnail/image.png",
    sourceUrl: "gs://que-backend-dev.appspot.com/testvideo.mp4",
    uploadedAt: new Date(),
    viewed: false,
    likedData: [],
    starredData: {},
  },
];

export default mockVideoCardData;
